[package]
name = "rust_performance"
version = "0.1.0"
authors = ["Marcin Szostak <luxurno@luxurno.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqp = "0.1.3"
